### ISSUE TITLE
I can't install it on OMV 3.0.62 (Erasmus) Linux 4.4.38-v7+

### ISSUE THREAD

**Issue by u63725** [OpenMediaVault-Plugin-Developers/openmediavault-shellinabox#2]
Reading package lists...
Building dependency tree...
>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-shellinabox 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openmediavault-shellinabox : Depends: openmediavault (= 3.0.13) but 3.0.62 is to be installed
E
:
Unable to correct problems, you have held broken packages.

<<< *************************************

**Comment by ryecoaaron** [comment]
Mentioning that you are using an RPi is very helpful in the future.  Should be fixed now.  I didn't put the plugin in the armhf architecture.
