### ISSUE TITLE
Unable to open nested browsing contents

### ISSUE THREAD

**Issue by f5Qz** [OpenMediaVault-Plugin-Developers/openmediavault-shellinabox#3]
From: https://bugtracker.openmediavault.org/view.php?id=1886

Unable to open the Shellinabox iframe. This is when connected through OpenVPN, but I remember this also happens when connect on local LAN. I get the following error message in Chrome (63.0.3239.132):

```
ext-all.js:22

Refused to frame 'http://10.8.0.1:32400/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
https://developer.chrome.com/apps/contentSecurityPolicy

**Comment by ryecoaaron** [comment]
There isn't much the plugin can do to fix this.  This is an nginx and OMV security setting.  The best solution is to open it in a new tab and not use iframes.
